CicekSepetiCloneDotNet/Pages/Cart/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;


namespace CicekSepetiCloneDotNet.Pages.Cart
{
    public class IndexModel : PageModel
    {
        // Sepet verilerinin tutulduğu liste (örnek bir ViewModel)
        public List<CartItemViewModel> cartItems = new List<CartItemViewModel>();
        public string user_id = "";
        string connectionString = ConnectionStrings.DefaultConnection;


        // OnGet: Sepet verilerini getirir
        public void OnGet()
        {
            user_id = Request.Query["user_id"];

            // Örnek: Sepet verilerini veritabanından çekiyoruz (simülasyon)
            cartItems = GetCartItemsFromDatabase(user_id);
        }

        // Ürün miktarını güncellemek için POST işlemi
        public void OnPostUpdateQuantity(int cartId, int quantity ,int user_id)
        {
            if (quantity <= 0)
            {
                ModelState.AddModelError("", "Miktar en az 1 olmalıdır.");
                Page();
            }

            // Veritabanında miktarı güncelle
            UpdateCartQuantity(cartId, quantity);

            // Tekrar sepete yönlendir
            Response.Redirect("/Cart/Index?user_id="+ user_id);
        
        }

    // Ürünü sepetten kaldırmak için POST işlemi
    public void OnPostRemoveFromCart(int cartId, int user_id)
        {
            // Veritabanından ürünü sil
            RemoveCartItem(cartId);

            // Tekrar sepete yönlendir
            Response.Redirect("/Cart/Index?user_id=" + user_id);
        }

        // Alışverişi tamamlamak için POST işlemi
      

        // Aşağıdaki metotlar örnek olarak veritabanı işlemlerini simüle eder:
        private List<CartItemViewModel> GetCartItemsFromDatabase(string user_id)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();


                    string sql = "GetCartDetailsByUser";



                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@UserId", user_id);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                CartItemViewModel cartProducts = new CartItemViewModel();
                                cartProducts.SellerName = reader.GetString(0);
                                cartProducts.ProductName = reader.GetString(1);
                                cartProducts.ProductQuantity = reader.GetInt32(2);
                                cartProducts.ProductImage = reader.GetString(3);
                                cartProducts.ProductPrice = reader.GetInt32(4);
                                cartProducts.ProductId = ""+reader.GetInt32(5);
                                cartProducts.cartId = ""+reader.GetInt32(6);
                                cartProducts.userId = user_id;


                                cartItems.Add(cartProducts);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            return cartItems;

        }

        private void UpdateCartQuantity(int cartId, int quantity)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();


                    string sql = "UPDATE tbl_cart SET quantity = @quantity WHERE CartId = @CartId";



                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@CartId", cartId);
                        command.Parameters.AddWithValue("@quantity", quantity);
                        command.ExecuteNonQuery();
                        
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

        }

        private void RemoveCartItem(int cartId)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = "DELETE FROM TBL_Cart WHERE CartId = @cartId";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@cartId", cartId);
                        command.ExecuteNonQuery();
                    }
                }

            }
            catch (Exception ex)
            {
                // Hata mesajını loglamak için
                Console.WriteLine(ex.Message); // Hata mesajını yazdırma (veya uygun loglama yapılabilir)
                Response.Redirect("/Error"); // Hata sayfasına yönlendirme
            }
        }

     
    }

    // Örnek ViewModel
    public class CartItemViewModel
    {
        public string userId;
        public string cartId;
        public string SellerName;
        public string ProductName;
        public int ProductQuantity;
        public string ProductImage;
        public int ProductPrice;
        public string ProductId;
    }
}

CicekSepetiCloneDotNet/Pages/Cart/Payment.cshtml.cs
using CicekSepetiCloneDotNet.Pages.AdminPage.Products;
using CicekSepetiCloneDotNet.Pages.AdminPage.Users;
using CicekSepetiCloneDotNet.Pages.SellerPage.Orders;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Net;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace CicekSepetiCloneDotNet.Pages.Cart
{
    public class PaymentModel : PageModel
    {
        string connectionString = ConnectionStrings.DefaultConnection;
        public string? buyer_id;
        public List<CartItemViewModel> cartItems = new List<CartItemViewModel>();
        public List<string> productIds = new List<string>();
        public UsersInfo buyerInfo = new UsersInfo();
        public int totalPrice = 0;
        public void OnGet()
        {
            buyer_id = Request.Query["user_id"];
            cartItems = GetCartItemsFromDatabase(buyer_id);// sepetteki ürünleri getirir. kullanıcı id'si ile
            getBuyerInfo(buyer_id);// kullanıcı bilgilerini getirir. kullanıcı id'si ile


        }
        public string paymentMethod;
        public string address;
        public void OnPost()
        {
            buyer_id = Request.Query["user_id"];

            paymentMethod = Request.Form["paymentMethod"];
            address = Request.Form["address"];

            List<CartItemViewModel> cartItems2 = GetCartItemsFromDatabase(buyer_id);
            createOrder(cartItems2, address);//ürünleri order tablosuna ekler

            List<string> productIds = GetProductIds(buyer_id);

            UsersInfo buyerInfo = getBuyerInfo(buyer_id);//kullanıcı bilgilerini getirir


            deactiveCartItems(cartItems2);//satın alınan ürünleri cart tablosundan siler

            Response.Redirect("/Cart/Successful");
        }

       

        private UsersInfo getBuyerInfo(string buyer_id)
        {
            try
            {
                //get user addres from database
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = "Select * from tbl_users where user_id=@buyer_id";

                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {

                        command.Parameters.AddWithValue("@buyer_id", buyer_id);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                buyerInfo.user_id = reader["user_id"].ToString();
                                buyerInfo.user_name = reader["user_name"].ToString();
                                buyerInfo.user_surname = reader["user_surname"].ToString();
                                buyerInfo.user_mail = reader["user_mail"].ToString();
                                buyerInfo.user_number = reader["user_number"].ToString();
                                buyerInfo.user_city = reader["user_city"].ToString();
                            }
                        }
                    }


                }
            }
            catch (Exception ex)
            {

                Console.WriteLine(ex.ToString());
            }
            return buyerInfo;
        }

        private void deactiveCartItems(List<CartItemViewModel> cartItems)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = "update TBL_cart set isActive=0 where cartId=@cartId";
                        

                    foreach (var item in cartItems)
                    {
                        using (SqlCommand command = new SqlCommand(sql, connection))
                        {
                            command.Parameters.AddWithValue("@cartId", item.cartId);


                            command.ExecuteNonQuery();
                        }

                    }

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }

        private void createOrder(List<CartItemViewModel> cartItems, string address)
        {
            //carttan çekilenleri order tablosuna ekle
            
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = "INSERT INTO TBL_orders " +
                        "(productId, userId,productQuantity,orderDate,isActive, isSent, PaymentMethod, Adress,Price) VALUES " +
                        "(@productId, @userId, @productQuantity, @orderDate, 1, 0,@PaymentMethod,@Adress, @price);";

                    foreach (var item in cartItems)
                    {
                        using (SqlCommand command = new SqlCommand(sql, connection))
                        {
                            command.Parameters.AddWithValue("@productId", item.ProductId);
                            command.Parameters.AddWithValue("@userId", item.userId);
                            command.Parameters.AddWithValue("@productQuantity", item.ProductQuantity);
                            command.Parameters.AddWithValue("@orderDate", DateTime.Now);
                            command.Parameters.AddWithValue("@PaymentMethod", paymentMethod);
                            command.Parameters.AddWithValue("@Adress", address);
                            command.Parameters.AddWithValue("@price", item.ProductPrice * item.ProductQuantity);

                            command.ExecuteNonQuery();
                        }
                        
                    }
                    
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

        }
      


        private List<CartItemViewModel> GetCartItemsFromDatabase(string user_id)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();


                    string sql = "GetCartDetailsByUser";



                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@UserId", user_id);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                CartItemViewModel cartProducts = new CartItemViewModel();
                                cartProducts.SellerName = reader.GetString(0);
                                cartProducts.ProductName = reader.GetString(1);
                                cartProducts.ProductQuantity = reader.GetInt32(2);
                                cartProducts.ProductImage = reader.GetString(3);
                                cartProducts.ProductPrice = reader.GetInt32(4);
                                cartProducts.ProductId = "" + reader.GetInt32(5);
                                cartProducts.cartId = "" + reader.GetInt32(6);
                                cartProducts.userId = user_id;
                                totalPrice += cartProducts.ProductPrice * cartProducts.ProductQuantity;
                                cartItems.Add(cartProducts);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            return cartItems;

        }
        private List<string> GetProductIds(string user_id)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();


                    string sql = "GetCartDetailsByUser";



                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@UserId", user_id);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                CartItemViewModel cartProducts = new CartItemViewModel();
                                cartProducts.ProductId = "" + reader.GetInt32(5);
                                productIds.Add(cartProducts.ProductId);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            return productIds;

        }
    }
}

CicekSepetiCloneDotNet/Pages/Cart/Successful.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CicekSepetiCloneDotNet.Pages.Cart
{
    public class Successful : PageModel
    {
        public void OnGet()
        {
            // Razor Page için sadece görüntüleme yapılacak.
            // Bu yüzden herhangi bir işlem yapmamıza gerek yok.
            // Sadece sayfayı göstermemiz yeterli olacak. Animasyon gösterielecek
        }
    }
}

CicekSepetiCloneDotNet/Pages/Cart/Index.cshtml
@page
@model CicekSepetiCloneDotNet.Pages.Cart.IndexModel
@{
    ViewData["Title"] = "Sepetim";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-5">
    <h1 class="text-center mb-4">Sepetim</h1>

    @if (Model.cartItems != null && Model.cartItems.Any())
    {
        <table class="table table-striped table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>Ürün</th>
                    <th>Satıcı</th>
                    <th>Fiyat</th>
                    <th>Miktar</th>
                    <th>Toplam</th>
                    <th>İşlem</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.cartItems)
                {
                    <tr>
                        <td>
                            <img src="~/assets/products/@item.ProductImage" alt="Ürün Görseli" class="img-thumbnail" style="width: 100px; height: 100px;" />
                            <span class="ms-2">@item.ProductName</span>
                        </td>
                        <td>@item.SellerName</td>
                        <td>@item.ProductPrice</td>
                        <td>
                            <form asp-page-handler="UpdateQuantity" method="post" class="d-inline">
                                <input type="hidden" name="user_id" value="@item.userId" />
                                <input type="hidden" name="CartId" value="@item.cartId" />
                                <input type="number" name="Quantity" value="@item.ProductQuantity" min="1" class="form-control d-inline-block w-50" />
                                <button type="submit" class="btn btn-sm btn-primary">Güncelle</button>
                            </form>
                        </td>
                        <td>@(item.ProductQuantity * item.ProductPrice)</td>
                        <td>
                            <form asp-page-handler="RemoveFromCart" method="post">
                                <input type="hidden" name="user_id" value="@item.userId" />
                                <input type="hidden" name="cartId" value="@item.cartId" />
                                <button type="submit" class="btn btn-sm btn-danger">Sil</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="text-end mt-4">
            <h4>Genel Toplam: @Model.cartItems.Sum(x => x.ProductQuantity * x.ProductPrice) ₺</h4>
            <a type="submit" class="btn btn-success" href="/Cart/Payment?user_id=@Model.user_id">Alışverişi Tamamla</a>
        </div>
    }
    else
    {
        <div class="alert alert-warning text-center" role="alert">
            Sepetinizde ürün bulunmamaktadır.
        </div>
    }
</div>

CicekSepetiCloneDotNet/Pages/Cart/Payment.cshtml
@page
@model CicekSepetiCloneDotNet.Pages.Cart.PaymentModel
@{
    var cartItems = Model.cartItems; // Sepet ürünleri
    //var totalPrice = cartItems.Sum(item => item.ProductPrice * item.Quantity); // Toplam tutar
}
<head>
    <link rel="stylesheet" href="~/css/payment.css" />
</head>
<div class="container">
    <h2 class="text-center">Ödeme Sayfası</h2>

    <!-- Kullanıcı Bilgileri Formu -->
    <form method="post" class="payment-form">
        <h4>Kullanıcı Bilgileri</h4>
        <div class="form-group">
            <label>Ad Soyad:  @Model.buyerInfo.user_name @Model.buyerInfo.user_surname</label>
        </div>
        <div class="form-group">
            <label>E-posta:  @Model.buyerInfo.user_mail</label>
        </div>
        <div class="form-group">
            <label >Telefon Numarası:  @Model.buyerInfo.user_number</label>
        </div>

        <!-- Adres Bilgileri -->
        <h4>Adres Bilgileri</h4>
        <div class="form-group">
            <input type="text" class="form-control" id="address" name="address" placeholder="Adresinizi girin" required>
        </div>
        <div class="form-group">
            <labe>Şehir:  @Model.buyerInfo.user_city</labe>
        </div>

        <!-- Ödeme Yöntemi -->
        <h4>Ödeme Yöntemi</h4>
        <div class="form-group">
            <select class="form-control" id="paymentMethod" name="paymentMethod" required>
                <option value="creditCard">Kredi Kartı</option>
                <option value="bankTransfer">Banka Havalesi</option>
                <option value="cashOnDelivery">Kapıda Ödeme</option>
            </select>
        </div>

        <!-- Sepet Özeti -->
        <h4>Sepet Özeti</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Ürün Görseli</th>
                    <th>Ürün Adı</th>
                    <th>Adet</th>
                    <th>Fiyat</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in cartItems)
                {
                    <tr>
                        <td>
                            <img src="~/assets/products/@item.ProductImage" alt="Ürün Görseli" style="width: 100px; height: auto;" />
                        </td>
                        <td>@item.ProductName</td>
                        <td>@item.ProductQuantity</td>
                        <td>@item.ProductPrice ₺</td>
                    </tr>
                }
                <tr>
                    <td class="text-left"><strong></strong></td>
                    <td class="text-left"><strong></strong></td>
                    <td class="text-left"><strong>Toplam Tutar:</strong></td>
                    <td><strong>₺ @Model.totalPrice</strong></td>
                </tr>
            </tbody>
        </table>

        <!-- Ödeme Butonu -->
        <button type="submit" class="btn btn-primary btn-block">Ödemeyi Tamamla</button>
    </form>
</div>

CicekSepetiCloneDotNet/Pages/Cart/Successful.cshtml
@page
@model CicekSepetiCloneDotNet.Pages.Cart.Successful
@{
    ViewData["Title"] = "Ödeme Başarılı";
}
<link rel="stylesheet" href="~/css/paymentSuccess.css" />

<div class="payment-status">
    <div id="loadingMessage" class="loading">
        Ödeme sürüyor...
    </div>
    <div id="successMessage" class="success hidden">
        Ödeme Başarılı!
    </div>
</div>


<script>
    // Minimum ve maksimum süreler (milisaniye cinsinden)
    const minTime = 3000; // 3 saniye
    const maxTime = 6000; // 6 saniye

    // Random süre belirle
    const waitTime = Math.floor(Math.random() * (maxTime - minTime + 1)) + minTime;

    // Mesaj elemanlarını al
    const loadingMessage = document.getElementById("loadingMessage");
    const successMessage = document.getElementById("successMessage");

    // Zamanlayıcı başlat
    setTimeout(() => {
        // "Ödeme sürüyor..." mesajını gizle
        loadingMessage.style.display = "none";

        // "Ödeme Başarılı!" mesajını göster
        successMessage.style.display = "block";
    }, waitTime);
</script>